name: Generate Third-Party Notices

on:
  push:
    branches:
      - main

env:
  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+repolinter-action@newrelic.com
  THIRD_PARTY_GIT_AUTHOR_NAME: Actionbot

jobs:
  job-generate-third-party-notices:
    runs-on: ubuntu-latest
    needs: job-checkout-and-build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: engine

      - name: Install OSS CLI
        run: |
          sudo npm install -g @newrelic/newrelic-oss-cli
      
      - name: Generate Third Party Notices
        working-directory: engine
        run: |
          if [ ! -f "third_party_manifest.json" ]; then
            echo "::error::third_party_manifest.json is missing. Must generate using the newrelic-oss-cli."
            exit 1
          fi
          # latest commit
          LATEST_COMMIT=$(git rev-parse HEAD)
          # latest commit where package.json was changed
          LAST_CHANGED_COMMIT=$(git log -1 --format=format:%H --full-diff package.json)
          if [ $LAST_CHANGED_COMMIT = $LATEST_COMMIT ]; then
            git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
            git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
            oss third-party manifest
            oss third-party notices
            git add third_party_manifest.json
            git add THIRD_PARTY_NOTICES.md
            
            git commit -m 'chore: update third-party manifest and notices [skip ci]'
            git push origin ${GITHUB_REF#/refs/heads/} 
          else
            echo "No change in package.json, not regenerating third-party notices"
          fi
